[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "witertools"
authors = [{name = "Doug Ransom", email = "doug@ransom.vip"}]
dynamic = ["version", "description"]
